# Link the C runtime statically so the executables run on a clean Windows install
# without the Visual C++ redistributable.
[target.x86_64-pc-windows-msvc]
rustflags = ["-C", "target-feature=+crt-static"]
